name: Komodo Actions
description: Implement some Komodo API methods for Github Actions
author: aboul

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: home
  color: green

# Define your inputs here.
inputs:
  komodo-url:
    description: 'Komodo server URL (e.g., https://komodo.example.com)'
    required: true
  api-key:
    description: 'Komodo API key'
    required: true
  api-secret:
    description: 'Komodo API secret'
    required: true
  kind:
    description: 'Type de ressource à déployer: stack | service | procedure'
    required: true
  patterns:
    description:
      'JSON array des noms ou patterns des ressources à déployer, ex:
      ["website","backend"]'
    required: true
  dry-run:
    description: Dry-run
    required: false
    default: 'false'

outputs:
  updates:
    description: 'A JSON representation of the update(s) returned by Komodo'

runs:
  using: 'node24'
  main: 'dist/index.js' # ton JS compilé depuis TypeScript
